# -*- coding: utf-8 -*-
"""Climate Change.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rCyK2WEtQH0UI8v1ap1Vnj6k-L42ur_4
"""

# Load the required libraries
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats
import matplotlib.pyplot as plt

# Function that takes filename as an argument and returns two dataframes
def readExcelFile(filename):
  data = pd.read_excel(filename)
  data = data.drop(data.columns[[1, 2, 3]],axis = 1)
  df1 = data.set_index(list(data.columns[[0]]))
  df2 = df1.transpose()
  return df1, df2

# Load the data
df1, df2 = readExcelFile('CO2 intensity (kg per kg of oil equivalent energy use).xls')

# Dataframe with years as columns
df1.head()

# Dataframe with country name as columns
# Drop some rows from 1960 to 1970
df2 = df2.drop(['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970'], axis = 0)
df2.head()

# Confirm the total number of null values
df2.isnull().sum()

# Drop all null values
df2 = df2.dropna()

#convert index column to datetime format
df2.index = pd.to_datetime(df2.index)
df2.head()

# Display basic descriptive statistics for all numeric columns
df2.describe()

# Calculating the mean
np.mean(df2)

# Calculating the standard deviation
np.std(df2)

# Plotting a correlation heatmap
data = df2
plt.figure(figsize = (5, 5))
sns.heatmap(df2.corr(), linewidths = 0.5, annot = True)
plt.show()

# Make a time series plot of CO2 Emissions
plt.rcParams["figure.figsize"] = [6, 6]

plt.plot(df2.index, df2['Angola'], label = "Angola")
plt.plot(df2.index, df2['Australia'], label = "Australia")
plt.plot(df2.index, df2['Austria'], label = "Austria" )
plt.plot(df2.index, df2['Azerbaijan'], label = "Azerbaijan")
plt.plot(df2.index, df2['Belgium'], label = "Belgium")
plt.xlabel('Year')
plt.ylabel('CO2 Intensity (kg per kg of oil equivalent energy use)')
plt.title('CO2 Intensty')
plt.legend(loc = "upper left")
plt.show()

# Make a bar plot of electric power consumption

df2.loc['2014-01-01'].plot.bar()
plt.ylabel('CO2 Intensity (kg per kg of oil equivalent energy use)')
plt.title('CO2 Intensty')
plt.legend()
plt.show()

# Pie Chart of CO2 Emissions
countries = ['Angola', 'Australia', 'Austria', 'Azerbaijan', 'Belgium']

plt.pie(np.mean(df2), labels = countries, autopct = '%.2f')

plt.title('Mean CO2 Intensty')
plt.show()